name: Upload CSV to GCP Cloud Storage

on:
  push:
    branches:
      - main
    # paths:
    #   - "*.csv"

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: cat credentials.json
        run: |
          echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json
          cat credentials.json

      - name: Authenticate to Google Cloud
        run: |
          # echo "${{ secrets.GCP_CREDENTIALS_JSON }}" > credentials.json
          gcloud auth activate-service-account --key-file=credentials.json
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}

      - name: Upload CSV files to GCP Cloud Storage
        run: |
          gsutil cp -r ./**/*.csv gs://${{ secrets.BUCKET_NAME }}

      # - name: Checkout repository
      #   uses: actions/checkout@v3

      # - name: Set up Google Cloud SDK
      #   uses: google-github-actions/setup-gcloud@v1
      #   with:
      #     project_id: ${{ secrets.GCP_PROJECT_ID }}
      #     credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      # - name: Upload CSV files to GCP Cloud Storage
      #   run: |
      #     for file in $(find . -name '*.csv'); do
      #       gsutil cp "$file" gs://test_az/
      #     done
