name: Upload CSV to GCP Bucket

on:
  push:
    branches:
      - main # Cambia a la rama que desees

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: holamundo
        run: echo "MY_SECRET=${{ secrets.pruebita}}" >> $GITHUB_ENV

      - name: prueba key
        shell: bash
        env:
          SUPER_SECRET: ${{ secrets.pruebita }}

        run: |

          echo "$SUPER_SECRET" >> prueba.txt
          cat prueba.txt
          echo "12121" >> ojete.txt
          cat ojete.txt
          echo "$GITHUB_ENV"
          ls /home/runner/work/_temp/_runner_file_commands/

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Upload CSV files to GCP Cloud Storage
        run: |
          for file in $(find . -name '*.csv'); do
            gsutil -m cp "$file" gs://test_az/
          done
      # - name: Upload CSV files to GCP Cloud Storage
      #   run: |
      #     for file in $(find . -name '*.csv'); do
      #       gsutil cp "$file" gs://test_az/
      #     done
