name: Upload CSV to GCP Bucket

on:
  push:
    branches:
      - main # Cambia a la rama que desees

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: prueba key
        run: |

          echo "${{ secrets.GCP_CREDENTIALS_JSON}},">> key.json
          truncate -s -2 key.json
          # cat key.json
          key="{$(cat key.json)}"
          echo "$key"

      - name: Configure GCP Credentials
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{secrets.GCP_PROJECT_ID}}
          credentials_json: "{$(cat key.json)}"

      - name: Upload CSV files to GCP Cloud Storage
        run: |
          for file in $(find . -name '*.csv'); do
            gsutil -m cp "$file" gs://test_az/
          done
      # - name: Upload CSV files to GCP Cloud Storage
      #   run: |
      #     for file in $(find . -name '*.csv'); do
      #       gsutil cp "$file" gs://test_az/
      #     done
