name: Upload CSV to GCP Bucket

on:
  push:
    branches:
      - main # Cambia a la rama que desees
    paths:
      # - "**.csv" # Solo se activará con cambios en archivos CSV

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - id: "auth"
        name: "Authenticate to Google Cloud"
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_CREDENTIALS_JSON }}"

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Upload CSV files to GCP Cloud Storage
        run: |
          # Listar todos los archivos CSV encontrados
          echo "Buscando archivos CSV..."
          find . -name '*.csv' -type f

          # Subir archivos usando gsutil con el flag -m para transferencias paralelas
          find . -name '*.csv' -type f | while read -r file; do
            echo "Subiendo archivo: $file"
            gsutil -m cp "$file" gs://test_az/
            
            if [ $? -eq 0 ]; then
              echo "✅ Archivo $file subido exitosamente"
            else
              echo "❌ Error al subir $file"
              exit 1
            fi
          done
