name: Upload CSV to GCP Cloud Storage

on:
  push:
    branches:
      - main
    paths:
      - '*.csv'

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.7.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_CREDENTIALS_JSON }}

      - name: Upload CSV files to GCP Cloud Storage
        run: |
          for file in $(find . -name '*.csv'); do
            gsutil cp "$file" gs://${{ secrets.BUCKET_NAME}}/
          done
